---
- hosts: all
  remote_user: root
  ###gather_facts: no
  vars:
    db_host: "spacewalk-postgresql.docker"
    db_pass: "root_pass"
    spacewalk_host: "spacewalk.docker" 
  tasks:
    ## Elasticseach instance ###
    # only one instance of elastic search can be created
    - name: Check if Docker runs
      shell:
        service docker status
      tags:
        - always

    - name: Run postgresql in Docker
      shell: |
        docker ps | grep "{{ db_host }}" ||
        docker run -d --name "{{ db_host }}" -h "{{ db_host }}" -p 5432:5432 -e POSTGRES_PASSWORD="{{ db_pass }}" postgres:9.6

    - name: Install pctl 9.6 to postgresql
      shell:
        docker exec {{ db_host }} /bin/bash -c "apt update && apt install postgresql-pltcl-9.6 -y"

    - name: Copy files to remote systems to build image for Docker
      copy: src={{ item }} dest=/root/{{ item }}
      with_items:
        - Dockerfile
        - jpackage-generic.repo
        - answer.txt
        - bin
        - bin/docker-spacewalk-setup.sh
        - bin/docker-spacewalk-run.sh

    - name: Build Docker image with spacewalk
      command:
        docker build -t spacewalk .

    - name: Install spacewalk from nigthly build
      command:
        docker run --name "{{ spacewalk_host }}" -h "{{ spacewalk_host }}" --link "{{ db_host }}:{{ db_host }}" -p 80:80 -p 443:443 -e POSTGRES_PASSWORD="{{ db_pass }}" spacewalk /root/docker-spacewalk-setup.sh

    - name: Run spacewalk server
      command:
        docker exec -d {{ spacewalk_host }} /root/docker-spacewalk-run.sh

    - name: Check if spacewalk runs
      shell:
        wget http://$( spacewalk_host )/
...

